version: "3"

services:
  react:
    image: nginx-react:1.2.0
    container_name: react_1.2.0
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      TZ: "Asia/Seoul"